#mysql
development:
  adapter: mysql
  database: footballsucks_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: footballsucks_test
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: footballsucks_production
  username: root
  password: 
  socket: /tmp/mysql.sock
